version: '3.8'

x-common:

12

database:

13

&db-environment

14

&db-password" from the end of the

15

16

17

19

20

21

22

23

24

25

26

lingel-environment

LIDL

MYSQL PASSWORD: &db-password "CHANGE_ME" MYSQL_ROOT_PASSWORD: "CHANGE_ME_TOO™

panel:

&panel-environment

# This URL should be the URL that your reverse proxy

routes to the panel server

APP_URL: "https://pterodactyl.example.com"

# A list of valid timezones can be found here: http://php.

net/manual/en/timezones.php

APP_TIMEZONE UTC"

APP_SERVICE_AUTHOR: "noreply@example.com"

TRUSTED_PROXIES: "*" # Set this to your proxy IP # Uncomment the line below and set to a non-empty

value if you want to use Let's Encrypt

27

28

# to generate an SSL, certificate for the Panel.

#LE_EMAIL:"

29

mail:

30

&mail-environment

31

MAIL FROM: "noreply@example.com"

32

MAIL DRIVER: "smtp"

33

MAIL_HOST: "mail"

34

MAIL PORT: "1025"

35

MAIL USERNAME:

36 MAIL PASSWORD:

37

MAIL ENCRYPTION: "true"
image: ghcr.io/pterodactyl/panel:latest

52

restart: always

53

ports:

54

"80:80"

55

"443:443"

56

links:

57

database

58

cache

59

70

71

72

73

74

75

76

77

78

79

30

volumes:

- "/srv/pterodactyl/var/:/app/var/"

- "/srv/pterodactyl/nginx/:/etc/nginx/http.d/"

- "/srv/pterodactyl/certs/:/etc/letsencrypt/"

"/srv/pterodactyl/logs/:/app/storage/logs

environment:

<<: [*panel-environment, *mail-environment]

DB_PASSWORD: *db-password

APP_ENV: "production"

APP_ENVIRONMENT_ONLY: "false"

CACHE DRIVER: "redis"

SESSION_DRIVER: "redis"

31

32

QUEUE_DRIVER: "redis"

REDIS_HOST: "cache"

33

34

DB_HOST: "database"

DB_PORT: "3306"

35 networks:

36

default:

37 ipam:

38

config:

89

subnet: 172.20.0.0/16
